# this is meant for running muliple containers in one yaml file
version: "3"
services:
  employee-jdbc:
    image: employee-jdbc
    ports:
      - "8080:8080"
    # networks:
    #   - employee-mysql
    depends_on:
      - mysqldb
 
  mysqldb:
    image: mysql:8
    # if networks not defined then default network will be created by docker which is "folder_name_default"
    # networks:
    #   - employee-mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=bootdb  

networks:
  employee-mysql: